---
- name: Determine if CentOS/RHEL 6
  include_tasks: rhel6.yml
  when: (ansible_facts['distribution'] == "RHEL" and ansible_facts['distribution_major_version'] == "6")

- name: Determine if CentOS/RHEL 7
  include_tasks: rhel7.yml
  when: (ansible_facts['distribution'] == "RHEL" and ansible_facts['distribution_major_version'] == "7")


      

   