---
- name: Describe RHEL 6
  debug:
    msg: "RHEL 6 Commands"

- name: Enable Splunk Boot Start
  command: sudo /opt/splunk/bin/splunk enable boot-start -user splunk

- name: Give Splunk User Owner Rights to /opt/splunk Recursively 
  command: sudo chown -R splunk:splunk /opt/splunk

- name: Change Splunk Startup Script Content
  lineinfile:
    path: /etc/init.d/splunk
    insertafter: "RETVAL=0"
    line: "insert User=Splunk"

- name: Reboot the Machine
  reboot:
